# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

networks:
    local:
        driver: bridge

services:

    riskharitasi:
        container_name : riskharitasi
        image          : riskharitasi:latest
        restart        : always
        build          : .

        networks:
            - local
        ports:
            - 3310:5000
        volumes:
            - .:/usr/src/riskharitasi